name: Docker Image CI
permissions: write-all

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish a Docker image for pixel-backend
        uses: macbre/push-to-ghcr@master
        with:
          dockerfile: Dockerfile
          image_name: bayudc/waifuseum-next
          github_token: ${{ secrets.GITHUB_TOKEN }}
